# -*- coding: utf-8 -*-
"""Credit Card Fraud Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KveN-QuLOClIpaT8cMLkFYvkRGpBCHUx
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

credit_data = pd.read_csv('/content/creditcard.csv')

credit_data.info()

credit_data.isna().sum()

"""# **Undersampling method to balance unbalanced dataset**"""

legit = credit_data[credit_data.Class == 0]
fraud = credit_data[credit_data.Class == 1]

print(legit.shape, fraud.shape)

credit_data.groupby(["Class"]).mean()

legit_sample = legit.sample(n=492)

new_df = pd.concat([fraud, legit_sample], axis=0)

new_df.shape

new_df.groupby(["Class"]).mean()

X = new_df.drop(columns='Class')
y = new_df['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=961)

clf = LogisticRegression(solver='lbfgs', max_iter=400)

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy_score(y_pred, y_test)

